### ISSUE TITLE
Can't get my ragdoll to work

### ISSUE THREAD

**Issue by Ipsider** [sergioabreu-g/active-ragdolls#1]
Hi Sergio,
let me say that I love your project. I want to use your code to animate my zombie character. I am having some trouble with the physics module I believe. You have any idea where I went wrong if I see something like this?
<img width="293" alt="Screenshot 2021-02-09 at 21 49 27" src="https://user-images.githubusercontent.com/9433900/107426569-b1243e00-6b20-11eb-92cf-c9b5388a30e3.png">

**Comment by sergioabreu-g** [comment]
I can't say with so little information. I don't know anything about your character hierarchy, components, model, etc. You should only see one model though, unless you manually activated the model of the animated character.

**Comment by Ipsider** [comment]
Yes, I know, very little information. I just activated the animated model for debugging purposes. Never mind though, I'll figure it out. Thanks for the repository! :)
