### ISSUE TITLE
ton of errors + warnings

### ISSUE THREAD

**Issue by tyler1d** [sergioabreu-g/active-ragdolls#2]
![image](https://user-images.githubusercontent.com/80140391/110193635-1955ff00-7e03-11eb-97b0-e1323379481f.png)
I dont know how to fix this, if you could respond to this thatll be great help. Thanks!

**Comment by tyler1d** [comment]
problem fixed!

**Comment by tyler1d** [comment]
I do have a question tho. Is there any way i could make this guy faster? Ive looked through so many scripts and cant fins anything

**Comment by tvw9** [comment]
> problem fixed!

how did you fixed this?
