### ISSUE TITLE
How to track player position with Active Ragdolls

### ISSUE THREAD

**Issue by TrongHieu90** [sergioabreu-g/active-ragdolls#4]
Hi,

It seems to me that the ActiveRagdoll gameobject does not change its position at all when the child GO physical dragdoll is moving.

How can i get the correct position of the player ?

**Comment by sergioabreu-g** [comment]
That's more of a philosophical question actually. What's the position of an Active Ragdoll? It's a collection of connected rigidbodies, so there's no single point you can call the center of the Active Ragdoll. You could use the center of mass, center of volume or just the position of the hips, for example. I would advise for the latter if you want to simplify things, just reference the hips Transform and use its position instead.

**Comment by TrongHieu90** [comment]
Hi,
Thanks for your answer. One more thing i would like to ask. There seems to be a way to self balance with input (setting balance mode to manual torque) But I cannot figure out how to balance the player correctly with movement input. Is there something im missing?

**Comment by sergioabreu-g** [comment]
I didn't use it for balance, but to be able to rotate the player in mid air. It is very hard to control, so I don't think you can maintain a ragdoll in a standing posture with that.
