### ISSUE TITLE
A question about the video "Active Ragdolls in Unity"

### ISSUE THREAD

**Issue by hellozjj** [sergioabreu-g/active-ragdolls#5]
Hi, you said in the video "Active Ragdolls in Unity": Euphoria uses much more than physics animation. 
I'm new to Euphoria and want to learn much more about it. But I can only find few introductions about it. Do you familiar with it? Can you say more in detail about Euphoria？ Or give me some links that can solve my problem?

**Comment by sergioabreu-g** [comment]
Euphoria is proprietary software, so there's not much you can learn about it unless you work at the company that makes it haha. You can look into the modding community of Rockstar's games if you're interested in that, there you might be able to tweak Euphoria inside games that use it, such as GTA V.

**Comment by hellozjj** [comment]
> Euphoria is proprietary software, so there's not much you can learn about it unless you work at the company that makes it haha. You can look into the modding community of Rockstar's games if you're interested in that, there you might be able to tweak Euphoria inside games that use it, such as GTA V.

Thanks.
Do you know how AI works in it's physics animation system?  Does it also have an animation body that the ragdoll needs to  "imitate" like your projects?

**Comment by sergioabreu-g** [comment]
> 
> 
> > Euphoria is proprietary software, so there's not much you can learn about it unless you work at the company that makes it haha. You can look into the modding community of Rockstar's games if you're interested in that, there you might be able to tweak Euphoria inside games that use it, such as GTA V.
> 
> Thanks. Do you know how AI works in it's physics animation system? Does it also have an animation body that the ragdoll needs to "imitate" like your projects?

I have no idea.
